#!/bin/bash
# Generate C header files with embedded user programs for ARM64
# Usage: ./scripts/embed-user-programs.sh [ARCH]

ARCH=${1:-arm64}
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

SHELL_ELF="$PROJECT_ROOT/user/shell/build/$ARCH/shell.elf"
HELLO_ELF="$PROJECT_ROOT/user/helloworld/build/$ARCH/hello.elf"
OUTPUT_DIR="$PROJECT_ROOT/src/include/kernel"
OUTPUT_FILE="$OUTPUT_DIR/embedded_programs.h"

echo "Generating embedded user programs for $ARCH..."

# Check if ELF files exist
if [ ! -f "$SHELL_ELF" ]; then
    echo "Warning: Shell ELF not found: $SHELL_ELF"
    SHELL_ELF=""
fi

if [ ! -f "$HELLO_ELF" ]; then
    echo "Warning: Hello ELF not found: $HELLO_ELF"
    HELLO_ELF=""
fi

# Generate header file
cat > "$OUTPUT_FILE" << 'EOF'
/**
 * @file embedded_programs.h
 * @brief Embedded user programs for ARM64 (auto-generated)
 * 
 * This file contains user programs embedded as byte arrays for ARM64,
 * which doesn't have a disk image like x86.
 * 
 * Generated by: scripts/embed-user-programs.sh
 */

#ifndef _KERNEL_EMBEDDED_PROGRAMS_H_
#define _KERNEL_EMBEDDED_PROGRAMS_H_

#include <types.h>

EOF

# Function to convert binary to C array
convert_to_c_array() {
    local input_file="$1"
    local array_name="$2"
    local size_name="$3"
    
    if [ -z "$input_file" ] || [ ! -f "$input_file" ]; then
        echo "/* $array_name not available */" >> "$OUTPUT_FILE"
        echo "static const uint8_t ${array_name}[] = { 0 };" >> "$OUTPUT_FILE"
        echo "static const uint32_t ${size_name} = 0;" >> "$OUTPUT_FILE"
        return
    fi
    
    local size=$(stat -f%z "$input_file" 2>/dev/null || stat -c%s "$input_file" 2>/dev/null)
    
    echo "/* $array_name: $(basename "$input_file") ($size bytes) */" >> "$OUTPUT_FILE"
    echo "static const uint8_t ${array_name}[] = {" >> "$OUTPUT_FILE"
    
    xxd -i < "$input_file" | sed 's/^/    /' >> "$OUTPUT_FILE"
    
    echo "};" >> "$OUTPUT_FILE"
    echo "static const uint32_t ${size_name} = $size;" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
}

# Convert shell.elf
convert_to_c_array "$SHELL_ELF" "embedded_shell_elf" "embedded_shell_size"

# Convert hello.elf
convert_to_c_array "$HELLO_ELF" "embedded_hello_elf" "embedded_hello_size"

# Close header guard
echo "#endif /* _KERNEL_EMBEDDED_PROGRAMS_H_ */" >> "$OUTPUT_FILE"

echo "Generated: $OUTPUT_FILE"
